; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:esp32-s3-devkitc-1-n16r8v]
;platform = espressif32
;board = esp32-s3-devkitc-1
;framework = arduino
;board_upload.flash_size = 16MB
;board_upload.maximum_size = 16777216
;board_build.arduino.memory_type = qio_opi
;board_build.filesystem = littlefs
;build_flags = 
;  -DBOARD_HAS_PSRAM
;  ; TFT_eSPI configuration
;  -D USER_SETUP_LOADED=1
;  -D GC9A01_DRIVER=1
;  -D TFT_WIDTH=240
;  -D TFT_HEIGHT=240
;  -D TFT_MOSI=11
;  -D TFT_SCLK=13
;  -D TFT_MISO=17  
;  -D TFT_DC=4
;  -D TFT_RST=6
;  -D USE_HSPI_PORT=1
;  -D TFT_CS=-1 ; Using manual CS
;  -D SPI_FREQUENCY=80000000
;  -D SMOOTH_FONT=1



[env:esp32-s3-intellar]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_mode = opi
board_upload.flash_size = 8MB
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI
    sparkfun/SparkFun VL53L5CX Arduino Library    
board_build.filesystem = littlefs

build_flags =
    -DUSE_HSPI_PORT
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ofast
    -DUSER_SETUP_LOADED=1
    -DSPI_FREQUENCY=80000000
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_MISO=9
    -DTFT_CS=-1
    -DTFT_DC=13
    -DTFT_RST=14
    -DTFT_CS_L=10
    -DTFT_CS_R=21


[env:esp32-s3-supermini-n4r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.filesystem = littlefs
board_build.partitions = default.csv
monitor_speed = 115200
board_build.arduino.cdc_on_boot = 1

build_flags = 
  ; --- Forçage de la configuration USB ---
  -D ARDUINO_USB_MODE=1
  ; --- Disable ToF Sensor ---
  ; --- Configuration du nombre d'yeux (1 ou 2) ---
  -D ARDUINO_USB_CDC_ON_BOOT=1  
  -DBOARD_HAS_PSRAM ; On garde l'activation de la PSRAM, c'est une caractéristique de la carte
  ; --- Configuration TFT_eSPI désactivée pour le débogage ---
  -D USER_SETUP_LOADED=1
  ; -D GC9A01_DRIVER=1 ; Ancien pilote
  -D ST7789_DRIVER=1  ; Nouveau pilote pour l'écran ST7789
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=11
  -D TFT_SCLK=12
  -D TFT_MISO=-1
  -D TFT_DC=9
  -D TFT_RST=8
  -D USE_HSPI_PORT=1
  -D TFT_CS=-1 ;  CS not available
  -D SPI_FREQUENCY=80000000
  -D SMOOTH_FONT=1
  

lib_deps = 
	; --- Dépendances désactivées pour le débogage ---
	sparkfun/SparkFun VL53L5CX Arduino Library@^1.0.3
	bodmer/TFT_eSPI@^2.5.43


[env:esp32-s3-original]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_mode = opi
board_upload.flash_size = 8MB
monitor_speed = 115200
lib_deps =
    bodmer/TFT_eSPI
    sparkfun/SparkFun VL53L5CX Arduino Library    
board_build.filesystem = littlefs

build_flags =
    -DUSE_HSPI_PORT
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ofast
    -DUSER_SETUP_LOADED=1
    -DSPI_FREQUENCY=80000000
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=13
    -DTFT_MISO=17
    -DTFT_CS=-1
    -DTFT_DC=4
    -DTFT_RST=6
    -DTFT_CS_L=5
    -DTFT_CS_R=7


[env:esp32-s3-waveshare-dualeye]
platform = espressif32@6.8.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_mode = opi
board_upload.flash_size = 8MB
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    bodmer/TFT_eSPI
    sparkfun/SparkFun VL53L5CX Arduino Library    
board_build.filesystem = littlefs

build_flags =
    -DUSE_HSPI_PORT
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Ofast
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=42
    -DTFT_SCLK=41
    -DTFT_MISO=40
    -DTFT_CS=-1
    -DTFT_DC=45
    -DTFT_RST=-1
    -DTFT_BL=-1
    -DTFT_BACKLIGHT_ON=HIGH
    -DTFT_CS_L=47
    -DTFT_CS_R=38
    -DSPI_FREQUENCY=20000000
