// Generated by tools/convert_android_res.py - do not edit by hand.
// Every artwork asset ported from the Android app's res/drawable.

import SwiftUI

/// Typed access to every Android drawable / mipmap on the iOS side.
enum AndroidAsset: String, CaseIterable {
    case aspirant = "aspirant"
    case badge_legend = "badge_legend"
    case badge_master = "badge_master"
    case badge_skilled = "badge_skilled"
    case badge_warrior = "badge_warrior"
    case bg_battle = "bg_battle"
    case bg_bcbr = "bg_bcbr"
    case bg_books = "bg_books"
    case bg_bubble_received = "bg_bubble_received"
    case bg_bubble_sent = "bg_bubble_sent"
    case bg_card_glass = "bg_card_glass"
    case bg_card_invite = "bg_card_invite"
    case bg_cat = "bg_cat"
    case bg_chat_wallpaper = "bg_chat_wallpaper"
    case bg_circle = "bg_circle"
    case bg_circle_dark = "bg_circle_dark"
    case bg_commerce = "bg_commerce"
    case bg_count_badge = "bg_count_badge"
    case bg_gaming_tab_indicator = "bg_gaming_tab_indicator"
    case bg_gaming_tab_track = "bg_gaming_tab_track"
    case bg_law = "bg_law"
    case bg_level_badge = "bg_level_badge"
    case bg_message_input = "bg_message_input"
    case bg_morning = "bg_morning"
    case bg_neet_pg = "bg_neet_pg"
    case bg_neet_pg_landscape = "bg_neet_pg_landscape"
    case bg_neet_ug = "bg_neet_ug"
    case bg_neet_ug_landscape = "bg_neet_ug_landscape"
    case bg_search = "bg_search"
    case bg_send_button = "bg_send_button"
    case bg_software = "bg_software"
    case bg_stat_card = "bg_stat_card"
    case bg_status_badge = "bg_status_badge"
    case bg_subject_tag = "bg_subject_tag"
    case bg_upsc = "bg_upsc"
    case circle_blue = "circle_blue"
    case circle_correct_ring = "circle_correct_ring"
    case circle_orange = "circle_orange"
    case custom_health_bar = "custom_health_bar"
    case custom_progress_bar = "custom_progress_bar"
    case dark_mode_24px = "dark_mode_24px"
    case default_avatar = "default_avatar"
    case default_img = "default_img"
    case expert = "expert"
    case explanation_bg_rounded = "explanation_bg_rounded"
    case grandmaster = "grandmaster"
    case grandmaster_widget = "grandmaster_widget"
    case ic_attach_file = "ic_attach_file"
    case ic_back = "ic_back"
    case ic_beginner = "ic_beginner"
    case ic_challenge_swords = "ic_challenge_swords"
    case ic_comment = "ic_comment"
    case ic_dark_mode = "ic_dark_mode"
    case ic_description = "ic_description"
    case ic_download = "ic_download"
    case ic_email = "ic_email"
    case ic_emoji_smile = "ic_emoji_smile"
    case ic_feed = "ic_feed"
    case ic_google_logo = "ic_google_logo"
    case ic_heart_filled = "ic_heart_filled"
    case ic_heart_outline = "ic_heart_outline"
    case ic_help = "ic_help"
    case ic_home = "ic_home"
    case ic_image_placeholder = "ic_image_placeholder"
    case ic_launcher_background = "ic_launcher_background"
    case ic_launcher_foreground = "ic_launcher_foreground"
    case ic_legend = "ic_legend"
    case ic_light_mode = "ic_light_mode"
    case ic_lock = "ic_lock"
    case ic_master = "ic_master"
    case ic_menu = "ic_menu"
    case ic_message = "ic_message"
    case ic_messenger = "ic_messenger"
    case ic_notification = "ic_notification"
    case ic_pdf_library = "ic_pdf_library"
    case ic_person = "ic_person"
    case ic_power_adrenaline = "ic_power_adrenaline"
    case ic_power_confuse = "ic_power_confuse"
    case ic_power_shield = "ic_power_shield"
    case ic_power_shock = "ic_power_shock"
    case ic_quiz = "ic_quiz"
    case ic_reels = "ic_reels"
    case ic_rookie = "ic_rookie"
    case ic_score = "ic_score"
    case ic_search = "ic_search"
    case ic_send = "ic_send"
    case ic_settings = "ic_settings"
    case ic_share = "ic_share"
    case ic_shield_effect = "ic_shield_effect"
    case ic_shock_effect = "ic_shock_effect"
    case ic_skilled = "ic_skilled"
    case ic_user_placeholder = "ic_user_placeholder"
    case ic_warrior = "ic_warrior"
    case light_mode_24px = "light_mode_24px"
    case medigyaan_logo = "medigyaan_logo"
    case nav_user_image = "nav_user_image"
    case neetpg = "neetpg"
    case option_background_selector = "option_background_selector"
    case option_background_selector_selected = "option_background_selector_selected"
    case option_box = "option_box"
    case option_correct = "option_correct"
    case option_selector = "option_selector"
    case option_selector_rounded = "option_selector_rounded"
    case option_selector_rounded_selected = "option_selector_rounded_selected"
    case option_selector_selected = "option_selector_selected"
    case option_wrong = "option_wrong"
    case rank_begginer = "rank_begginer"
    case rank_rookie = "rank_rookie"
    case scholar = "scholar"
    case search_bg_shape = "search_bg_shape"
    case shape_rect_border = "shape_rect_border"
    case spinner_background = "spinner_background"
    case tab_selected_bg = "tab_selected_bg"
    case thesis_scholar_logo = "thesis_scholar_logo"
    case timer_bg_rounded = "timer_bg_rounded"
    case widget_bg = "widget_bg"

    var image: Image { Image(rawValue) }

    /// Icons Android draws with `android:tint`; tint with the app palette.
    static let templateIcons: Set<AndroidAsset> = [
        .bg_status_badge,
        .dark_mode_24px,
        .default_img,
        .ic_attach_file,
        .ic_challenge_swords,
        .ic_comment,
        .ic_description,
        .ic_download,
        .ic_email,
        .ic_feed,
        .ic_heart_filled,
        .ic_heart_outline,
        .ic_help,
        .ic_home,
        .ic_image_placeholder,
        .ic_light_mode,
        .ic_lock,
        .ic_menu,
        .ic_message,
        .ic_messenger,
        .ic_notification,
        .ic_pdf_library,
        .ic_person,
        .ic_reels,
        .ic_score,
        .ic_search,
        .ic_send,
        .ic_settings,
        .ic_share,
        .ic_user_placeholder,
        .light_mode_24px,
        .nav_user_image,
        .timer_bg_rounded,
    ]
}
