"""Server connection management for MCP Client for Ollama.

This module handles connections to one or more MCP servers, including setup,
initialization, and communication.
"""

import asyncio
import os
import shutil
from contextlib import AsyncExitStack
from typing import Dict, List, Any, Optional, Tuple
from rich.console import Console
from rich.panel import Panel
from mcp import ClientSession, Tool
from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp.client.sse import sse_client
from mcp.client.streamable_http import streamablehttp_client

from .discovery import process_server_paths, process_server_urls, parse_server_configs, parse_server_config_mapping, load_claude_desktop_servers, deduplicate_servers
from ..utils.constants import MCP_PROTOCOL_VERSION

class ServerConnector:
    """Manages connections to one or more MCP servers.

    This class handles establishing connections to MCP servers, either from
    individual script paths or from configuration files, and managing the
    tools provided by those servers.
    """

    def __init__(self, exit_stack: AsyncExitStack, console: Optional[Console] = None):
        """Initialize the ServerConnector.

        Args:
            exit_stack: AsyncExitStack to manage server connections
            console: Rich console for output (optional)
        """
        self.exit_stack = exit_stack
        self.console = console or Console()
        self.sessions = {}  # Dict to store multiple sessions
        self.available_tools = []  # List to store all available tools
        self.enabled_tools = {}  # Dict to store tool enabled status
        self.session_ids = {}  # Dict to store session IDs for HTTP connections
        self.prompts_by_server = {}  # Dict to store prompts grouped by server
        self.resources_by_server = {}  # Dict to store resources grouped by server
        self.templates_by_server = {}  # Dict to store resource templates grouped by server

    async def connect_to_servers(self, server_paths=None, server_urls=None, config_path=None, claude_desktop=False, server_configs=None) -> Tuple[dict, list, dict, dict, dict, dict]:
        """Connect to one or more MCP servers

        Args:
            server_paths: List of paths to server scripts (.py or .js)
            server_urls: List of URLs for SSE or Streamable HTTP servers
            config_path: Path to JSON config file with server configurations
            claude_desktop: Whether to load servers from Claude Desktop's config
            server_configs: Pre-built ``mcpServers`` configuration mapping
                with server names as keys and configuration entries as values.
                Used to connect to multiple servers at once (e.g., from merged
                scopes generated by `ollmcp mcp add`)

        Returns:
            Tuple of (sessions, available_tools, enabled_tools, prompts_by_server, resources_by_server, templates_by_server)
        """
        all_servers = []

        # Process a pre-built mcpServers mapping
        if server_configs:
            mapping_servers = parse_server_config_mapping(server_configs)
            for server in mapping_servers:
                self.console.print(f"[cyan]Found configured server: {server['name']}[/cyan]")
            all_servers.extend(mapping_servers)

        # Process server paths
        if server_paths:
            script_servers = process_server_paths(server_paths)
            for server in script_servers:
                self.console.print(f"[cyan]Found server script: {server['path']}[/cyan]")
            all_servers.extend(script_servers)

        # Process server URLs
        if server_urls:
            url_servers = process_server_urls(server_urls)
            for server in url_servers:
                self.console.print(f"[cyan]Found server URL: {server['url']} (type: {server['type']})[/cyan]")
            all_servers.extend(url_servers)

        # Process config file
        if config_path:
            try:
                config_servers = parse_server_configs(config_path)
                for server in config_servers:
                    self.console.print(f"[cyan]Found server in config: {server['name']}[/cyan]")
                all_servers.extend(config_servers)
            except Exception as e:
                self.console.print(f"[red]Error loading server configurations: {str(e)}[/red]")

        # Load Claude Desktop servers if requested
        if claude_desktop:
            desktop_servers = load_claude_desktop_servers()
            for server in desktop_servers:
                self.console.print(f"[cyan]Found Claude Desktop server: {server['name']}[/cyan]")
            all_servers.extend(desktop_servers)

        # The sources above are independent, so the same endpoint can arrive
        # twice and distinct endpoints can arrive with the same name. Resolve
        # both before connecting, or the second connection overwrites the first.
        all_servers, notices = deduplicate_servers(all_servers)
        for notice in notices:
            self.console.print(f"[yellow]{notice}[/yellow]")

        if not all_servers:
            self.console.print(Panel(
                "[yellow]No servers specified or all servers were invalid.[/yellow]\n"
                "The client will continue without tool support.",
                title="Warning", border_style="yellow", expand=False
            ))
            return self.sessions, self.available_tools, self.enabled_tools, self.prompts_by_server, self.resources_by_server, self.templates_by_server

        # Connect to each server
        for server in all_servers:
            await self._connect_to_server(server)

        if not self.sessions:
            self.console.print(Panel(
                "[bold red]Could not connect to any MCP servers![/bold red]\n"
                "Check that server paths exist and are accessible.",
                title="Error", border_style="red", expand=False
            ))

        return self.sessions, self.available_tools, self.enabled_tools, self.prompts_by_server, self.resources_by_server, self.templates_by_server

    async def _connect_to_server(self, server: Dict[str, Any]) -> bool:
        """Connect to a single MCP server

        Args:
            server: Server configuration dictionary

        Returns:
            bool: True if connection was successful, False otherwise
        """
        server_name = server["name"]
        self.console.print(f"[cyan]Connecting to server: {server_name}[/cyan]")

        # Tracks whether the MCP handshake completed, so a cancellation raised
        # later (while querying capabilities) is not reported as the server
        # failing to answer initialize.
        initialized = False

        try:
            server_type = server.get("type", "script")
            session = None

            # Use a local exit stack for this connection attempt.  On failure
            # it exits immediately, closing the transport and clearing any
            # cancelled anyio scope so it cannot leak into later operations.
            # On success, contexts are transferred to self.exit_stack via pop_all().
            async with AsyncExitStack() as local_stack:

                # Connect based on server type
                if server_type == "sse":
                    # Connect to SSE server
                    url = self._get_url_from_server(server)
                    if not url:
                        self.console.print(f"[red]Error: SSE server {server_name} missing URL[/red]")
                        return False

                    headers = self._get_headers_from_server(server)

                    # Connect using SSE transport
                    sse_transport = await local_stack.enter_async_context(sse_client(url, headers=headers))
                    read_stream, write_stream = sse_transport
                    session = await local_stack.enter_async_context(ClientSession(read_stream, write_stream))

                elif server_type == "streamable_http":
                    # Connect to Streamable HTTP server
                    url = self._get_url_from_server(server)
                    if not url:
                        self.console.print(f"[red]Error: HTTP server {server_name} missing URL[/red]")
                        return False

                    headers = self._get_headers_from_server(server)

                    # Use the streamablehttp_client for Streamable HTTP connections
                    transport = await local_stack.enter_async_context(
                        streamablehttp_client(url, headers=headers)
                    )
                    read_stream, write_stream, session_info = transport
                    session = await local_stack.enter_async_context(ClientSession(read_stream, write_stream))

                    # Store session ID if provided
                    if hasattr(session_info, 'session_id') and session_info.session_id:
                        self.session_ids[server_name] = session_info.session_id

                elif server_type == "script":
                    # Connect to script-based server using STDIO
                    server_params = self._create_script_params(server)
                    if server_params is None:
                        return False

                    stdio_transport = await local_stack.enter_async_context(stdio_client(server_params))
                    read_stream, write_stream = stdio_transport
                    session = await local_stack.enter_async_context(ClientSession(read_stream, write_stream))

                else:
                    # Connect to config-based server using STDIO
                    server_params = self._create_config_params(server)
                    if server_params is None:
                        return False

                    stdio_transport = await local_stack.enter_async_context(stdio_client(server_params))
                    read_stream, write_stream = stdio_transport
                    session = await local_stack.enter_async_context(ClientSession(read_stream, write_stream))

                # Initialize the session and capture capabilities
                init_result = await session.initialize()
                initialized = True

                # Success — transfer connection contexts to the main exit_stack.
                # local_stack is now empty; its __aexit__ becomes a no-op.
                await self.exit_stack.enter_async_context(local_stack.pop_all())

            # Store the session
            self.sessions[server_name] = {
                "session": session,
                "tools": []
            }

            # Get tools from this server if capability is present
            server_tools = []
            capabilities = getattr(init_result, 'capabilities', None)
            if capabilities and getattr(capabilities, 'tools', None):
                try:
                    response = await session.list_tools()
                    # Store and merge tools, prepending server name to avoid conflicts
                    for tool in response.tools:
                        # Create a qualified name for the tool that includes the server
                        qualified_name = f"{server_name}.{tool.name}"
                        # Clone the tool but update the name
                        tool_copy = Tool(
                            name=qualified_name,
                            description=f"[{server_name}] {tool.description}" if hasattr(tool, 'description') else f"Tool from {server_name}",
                            inputSchema=tool.inputSchema,
                            outputSchema=tool.outputSchema if hasattr(tool, 'outputSchema') else None
                        )
                        server_tools.append(tool_copy)
                        self.enabled_tools[qualified_name] = True
                except asyncio.CancelledError:
                    self.console.print(f"[yellow]Warning: Listing tools from {server_name} was cancelled; continuing without them[/yellow]")
                except Exception as e:
                    self.console.print(f"[yellow]Warning: Failed to list tools from {server_name}: {str(e)}[/yellow]")
            else:
                self.console.print(f"[dim]Server {server_name} does not support tools capability[/dim]")

            self.sessions[server_name]["tools"] = server_tools
            self.available_tools.extend(server_tools)

            # Get prompts from this server if capability is present
            server_prompts = []
            if capabilities and getattr(capabilities, 'prompts', None):
                try:
                    prompts_response = await session.list_prompts()
                    server_prompts = prompts_response.prompts if hasattr(prompts_response, 'prompts') else []
                    if server_prompts:
                        self.prompts_by_server[server_name] = server_prompts
                except asyncio.CancelledError:
                    self.console.print(f"[yellow]Warning: Listing prompts from {server_name} was cancelled; continuing without them[/yellow]")
                except Exception as e:
                    self.console.print(f"[yellow]Warning: Failed to list prompts from {server_name}: {str(e)}[/yellow]")
            else:
                self.console.print(f"[dim]Server {server_name} does not support prompts capability[/dim]")

            # Get resources (static list + templates) if capability is present
            server_resources = []
            server_templates = []
            if capabilities and getattr(capabilities, 'resources', None):
                try:
                    resources_response = await session.list_resources()
                    server_resources = resources_response.resources if hasattr(resources_response, 'resources') else []
                    if server_resources:
                        self.resources_by_server[server_name] = server_resources
                except asyncio.CancelledError:
                    self.console.print(f"[yellow]Warning: Listing resources from {server_name} was cancelled; continuing without them[/yellow]")
                except Exception as e:
                    self.console.print(f"[yellow]Warning: Failed to list resources from {server_name}: {str(e)}[/yellow]")
                try:
                    templates_response = await session.list_resource_templates()
                    server_templates = templates_response.resourceTemplates if hasattr(templates_response, 'resourceTemplates') else []
                    if server_templates:
                        self.templates_by_server[server_name] = server_templates
                except asyncio.CancelledError:
                    self.console.print(f"[yellow]Warning: Listing resource templates from {server_name} was cancelled; continuing without them[/yellow]")
                except Exception as e:
                    self.console.print(f"[yellow]Warning: Failed to list resource templates from {server_name}: {str(e)}[/yellow]")
                summary_parts = []
                if server_resources:
                    summary_parts.append(f"{len(server_resources)} resource(s)")
                if server_templates:
                    summary_parts.append(f"{len(server_templates)} template(s)")
                if summary_parts:
                    self.console.print(f"[dim]  {server_name}: {', '.join(summary_parts)}[/dim]")
                else:
                    self.console.print(f"[dim]  {server_name} has resources capability but returned none[/dim]")
            else:
                self.console.print(f"[dim]Server {server_name} does not support resources capability[/dim]")

            prompt_count_msg = f" and {len(server_prompts)} prompt(s)" if server_prompts else ""
            resource_count_msg = f" and {len(server_resources) + len(server_templates)} resource(s)/template(s)" if (server_resources or server_templates) else ""
            self.console.print(f"[green]Successfully connected to {server_name} with {len(server_tools)} tool(s){prompt_count_msg}{resource_count_msg}[/green]")
            return True

        except asyncio.CancelledError:
            self._discard_server_state(server_name)
            if initialized:
                self.console.print(
                    f"[red]Error connecting to {server_name}: Connection dropped after a "
                    f"successful MCP initialization.[/red]"
                )
            else:
                self.console.print(
                    f"[red]Error connecting to {server_name}: Server did not respond to MCP "
                    f"initialization. Verify the URL serves an MCP endpoint, not a regular web "
                    f"page or other service.[/red]"
                )
            return False
        except FileNotFoundError as e:
            self._discard_server_state(server_name)
            self.console.print(f"[red]Error connecting to {server_name}: File not found - {str(e)}[/red]")
            return False
        except PermissionError:
            self._discard_server_state(server_name)
            self.console.print(f"[red]Error connecting to {server_name}: Permission denied[/red]")
            return False
        except Exception as e:
            self._discard_server_state(server_name)
            sub_exceptions = getattr(e, 'exceptions', None)
            if sub_exceptions:
                for sub in sub_exceptions:
                    self.console.print(f"[red]Error connecting to {server_name}: {str(sub)}[/red]")
            else:
                self.console.print(f"[red]Error connecting to {server_name}: {str(e)}[/red]")
            return False

    def _create_script_params(self, server: Dict[str, Any]) -> Optional[StdioServerParameters]:
        """Create server parameters for a script-type server

        Args:
            server: Server configuration dictionary

        Returns:
            StdioServerParameters or None if invalid
        """
        path = server["path"]
        is_python = path.endswith('.py')
        is_js = path.endswith('.js')

        if not (is_python or is_js):
            self.console.print(f"[yellow]Warning: Server script {path} must be a .py or .js file. Skipping.[/yellow]")
            return None

        command = "python" if is_python else "node"

        # Validate the command exists in PATH
        if not shutil.which(command):
            self.console.print(f"[yellow]Warning: Command '{command}' not found in PATH. Skipping server {server['name']}.[/yellow]")
            return None

        return StdioServerParameters(
            command=command,
            args=[path],
            env=None
        )

    def _create_config_params(self, server: Dict[str, Any]) -> Optional[StdioServerParameters]:
        """Create server parameters for a config-type server

        Args:
            server: Server configuration dictionary

        Returns:
            StdioServerParameters or None if invalid
        """
        server_config = server["config"]
        command = server_config.get("command")

        # Validate the command exists in PATH
        if not command or not shutil.which(command):
            self.console.print(f"[yellow]Warning: Command '{command}' for server '{server['name']}' not found in PATH. Skipping.[/yellow]")
            return None

        args = server_config.get("args", [])
        env = server_config.get("env")

        # Fix and validate directory arguments
        fixed_args, dir_exists, missing_dir = self._fix_directory_args(args)

        if not dir_exists:
            self.console.print(f"[yellow]Warning: Server '{server['name']}' specifies a directory that doesn't exist: {missing_dir}[/yellow]")
            self.console.print(f"[yellow]Skipping server '{server['name']}'[/yellow]")
            return None

        return StdioServerParameters(
            command=command,
            args=fixed_args,
            env=env
        )

    def _fix_directory_args(self, args: List[str]) -> Tuple[List[str], bool, Optional[str]]:
        """Fix common issues with directory arguments and validate directory existence

        Args:
            args: List of command line arguments

        Returns:
            Tuple containing:
            - List of fixed arguments
            - bool indicating if all directories exist
            - Optional[str] containing the first missing directory path if any
        """
        if not args:
            return args, True, None

        fixed_args = args.copy()

        for i, arg in enumerate(fixed_args):
            if arg == "--directory" and i + 1 < len(fixed_args):
                dir_path = fixed_args[i+1]

                # If the path is a file, use its parent directory
                if os.path.isfile(dir_path) and (dir_path.endswith('.py') or dir_path.endswith('.js')):
                    self.console.print(f"[yellow]Warning: Server specifies a file as directory: {dir_path}[/yellow]")
                    self.console.print(f"[green]Automatically fixing to use parent directory instead[/green]")
                    dir_path = os.path.dirname(dir_path) or '.'
                    fixed_args[i+1] = dir_path

                # Check if directory exists
                if not os.path.exists(dir_path):
                    return fixed_args, False, dir_path

        return fixed_args, True, None

    def get_sessions(self) -> Dict[str, Any]:
        """Get the current server sessions

        Returns:
            Dict of server sessions
        """
        return self.sessions

    def get_available_tools(self) -> List[Tool]:
        """Get the available tools from all connected servers

        Returns:
            List of available tools
        """
        return self.available_tools

    def get_enabled_tools(self) -> Dict[str, bool]:
        """Get the current enabled status of all tools

        Returns:
            Dict mapping tool names to enabled status
        """
        return self.enabled_tools

    def set_tool_status(self, tool_name: str, enabled: bool):
        """Set the enabled status of a specific tool

        Args:
            tool_name: Name of the tool to modify
            enabled: Whether the tool should be enabled
        """
        if tool_name in self.enabled_tools:
            self.enabled_tools[tool_name] = enabled

    def enable_all_tools(self):
        """Enable all available tools"""
        for tool_name in self.enabled_tools:
            self.enabled_tools[tool_name] = True

    def disable_all_tools(self):
        """Disable all available tools"""
        for tool_name in self.enabled_tools:
            self.enabled_tools[tool_name] = False

    def _get_url_from_server(self, server: Dict[str, Any]) -> Optional[str]:
        """Extract URL from server configuration.

        Args:
            server: Server configuration dictionary

        Returns:
            URL string or None if not found
        """
        # Try to get URL directly from server dict
        url = server.get("url")

        # If not there, try the config subdict
        if not url and "config" in server:
            url = server["config"].get("url")

        return url

    def _get_headers_from_server(self, server: Dict[str, Any]) -> Dict[str, str]:
        """Extract headers from server configuration.

        Args:
            server: Server configuration dictionary

        Returns:
            Dictionary of headers with lowercase keys
        """
        # Try to get headers directly from server dict
        headers = server.get("headers", {})

        # If not there, try the config subdict
        if not headers and "config" in server:
            headers = server["config"].get("headers", {})

        # Normalize all header names to lowercase per RFC 7230
        headers = {k.lower(): v for k, v in headers.items()}

        # Always add MCP Protocol Version header for HTTP connections
        server_type = server.get("type", "script")
        if server_type in ["sse", "streamable_http"]:
            headers["mcp-protocol-version"] = MCP_PROTOCOL_VERSION

        return headers

    def _discard_server_state(self, server_name: str) -> None:
        """Drop any state a failed connection attempt already registered.

        Capabilities are queried after the session is stored, so a failure
        partway through can leave a server registered as connected. Tools are
        matched by their qualified "<server>.<tool>" prefix to also cover a
        tools loop that only partially completed.

        Args:
            server_name: Name of the server whose partial state to remove
        """
        prefix = f"{server_name}."
        self.sessions.pop(server_name, None)
        self.session_ids.pop(server_name, None)
        self.prompts_by_server.pop(server_name, None)
        self.resources_by_server.pop(server_name, None)
        self.templates_by_server.pop(server_name, None)
        self.available_tools[:] = [t for t in self.available_tools if not t.name.startswith(prefix)]
        for qualified_name in [n for n in self.enabled_tools if n.startswith(prefix)]:
            del self.enabled_tools[qualified_name]

    async def disconnect_all_servers(self):
        """Disconnect from all servers and reset state"""
        # Close all existing connections via exit stack
        await self.exit_stack.aclose()

        # Create a new exit stack for future connections
        self.exit_stack = AsyncExitStack()

        # Clear all state
        self.sessions.clear()
        self.available_tools.clear()
        self.enabled_tools.clear()
        self.session_ids.clear()
        self.prompts_by_server.clear()
