"""File-selection / filtering rules for the offload daemon.

Three ``kind``s, controlled by :class:`PolicyConfig`:

* ``recording`` \u2014 ``/var/tank/recordings/*.avi`` older than
  ``recording_max_age_days`` (default 30). Camera clips are the
  biggest source of disk pressure in production; this is the kind
  that hits threshold most often.
* ``log``       \u2014 ``/var/tank/logs/*.log`` greater than
  ``log_min_bytes`` (default 50 MB). We never offload partial
  live logs; we offload rotated/archived logs only.
* ``db_snapshot`` \u2014 ``/var/tank/data/*.tar.gz`` (or *.tgz) older than
  ``db_snapshot_max_age_days`` (default 7). We deliberately do NOT
  offload raw sqlite ``*.db`` while a process holds them; only
  snapshots generated by ``tank_nas`` make it onto the wire.

The hard ``EXCLUDED_PREFIXES`` are absolute path exclusions that
can never be offloaded: live databases (``*.db`` while a processing
holds the file), ``/dev``/``/sys``/``/proc``/``/tmp`` (transient or
kernel pseudo-fs).
"""
from __future__ import annotations

import dataclasses
import glob
import logging
import os
import re
import time
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Optional, Tuple

_LOG = logging.getLogger("tank_offload.policy")


# A path can never be offloaded if it lives under one of these
# mount-point prefixes or matches one of these suffixes.
EXCLUDED_PREFIXES: Tuple[str, ...] = (
    "/dev", "/sys", "/proc", "/tmp", "/run",
)
EXCLUDED_SUFFIXES: Tuple[str, ...] = (
    ".db-wal", ".db-shm",     # active SQLite write-ahead / shared-memory maps
    ".db-journal",            # rollback journal (rare)
)


@dataclass
class PolicyConfig:
    """Tunable thresholds + paths. Defaults match the thinker's blueprint."""

    # Where to look
    recordings_glob: str = "/var/tank/recordings/*.avi"
    logs_glob: str = "/var/tank/logs/*.log"
    db_snapshot_glob: str = "/var/tank/data/*.tar.gz"

    # Age thresholds
    recording_max_age_days: float = 30.0
    db_snapshot_max_age_days: float = 7.0

    # Size thresholds
    log_min_bytes: int = 50 * 1024 * 1024   # 50 MB

    # How many of each kind to take per sweep. Keeps a single sweep
    # bounded so the queue never starves the watcher.
    max_per_kind: int = 50


# Item kinds \u2014 stable strings used as SQLite column + ROS payload tag.
KIND_RECORDING = "recording"
KIND_LOG = "log"
KIND_DB_SNAPSHOT = "db_snapshot"
ALL_KINDS: Tuple[str, ...] = (KIND_RECORDING, KIND_LOG, KIND_DB_SNAPSHOT)


@dataclass
class Candidate:
    """A file the policy wants offloaded. ``kind`` is one of ALL_KINDS."""

    path: str
    size_bytes: int
    mtime: float
    kind: str
    reason: str = ""

    def as_dict(self) -> Dict:
        return dataclasses.asdict(self)


def _is_excluded(path: str) -> Optional[str]:
    """Return the rule that excludes ``path`` (or ``None`` to admit)."""
    norm = os.path.normpath(path)
    for prefix in EXCLUDED_PREFIXES:
        if norm == prefix or norm.startswith(prefix + os.sep):
            return f"under {prefix}/"
    for suffix in EXCLUDED_SUFFIXES:
        if norm.endswith(suffix):
            return f"suffix {suffix!r}"
    # Defensive: refuse buckets / devices / pseudo files.
    try:
        st = os.stat(norm)
    except OSError:
        return "stat failed"
    if not os.path.isfile(norm):
        return "not a regular file"
    if st.st_size == 0:
        return "zero size"
    if not (st.st_mode & 0o400):
        return "no read permission"
    return None


def _scan_glob(pattern: str, max_age_days: float, min_bytes: int) \
        -> List[Candidate]:
    """Walk a glob and produce :class:`Candidate`s that pass both filters."""
    out: List[Candidate] = []
    now = time.time()
    age_cutoff = now - max_age_days * 86400.0 if max_age_days > 0 else float("inf")
    for raw in sorted(glob.glob(pattern)):
        norm = os.path.normpath(raw)
        exc = _is_excluded(norm)
        if exc:
            continue
        try:
            st = os.stat(norm)
        except OSError as exc:
            _LOG.debug("skip %s: stat failed (%s)", norm, exc)
            continue
        if st.st_size < min_bytes:
            continue
        if st.st_mtime > age_cutoff:
            continue
        out.append(Candidate(
            path=norm,
            size_bytes=st.st_size,
            mtime=st.st_mtime,
            kind="?",
            reason="",
        ))
    return out


class OffloadPolicy:
    """Apply :class:`PolicyConfig` rules. Stateless except for the
    ``now_fn`` knob (tests can pass a deterministic clock)."""

    def __init__(self, config: Optional[PolicyConfig] = None,
                 *, now_fn=None) -> None:
        self.config = config or PolicyConfig()
        self._now_fn = now_fn or time.time

    def candidates(self, kinds: Iterable[str] = ALL_KINDS) -> List[Candidate]:
        """Return the union of Candidates sorted largest-first."""
        cfg = self.config
        out: List[Candidate] = []
        if KIND_RECORDING in kinds:
            for c in _scan_glob(cfg.recordings_glob,
                                cfg.recording_max_age_days,
                                min_bytes=1):
                c.kind = KIND_RECORDING
                c.reason = (f"older than "
                            f"{cfg.recording_max_age_days:.0f}d")
                out.append(c)
            out.sort(key=lambda c: c.mtime)   # oldest-first for recordings
        if KIND_LOG in kinds:
            for c in _scan_glob(cfg.logs_glob,
                                max_age_days=0,
                                min_bytes=cfg.log_min_bytes):
                c.kind = KIND_LOG
                c.reason = (f"size >= {cfg.log_min_bytes} bytes")
                out.append(c)
            out.sort(key=lambda c: c.size_bytes, reverse=True)   # biggest-first
        if KIND_DB_SNAPSHOT in kinds:
            for c in _scan_glob(cfg.db_snapshot_glob,
                                cfg.db_snapshot_max_age_days,
                                min_bytes=1):
                c.kind = KIND_DB_SNAPSHOT
                c.reason = (f"older than "
                            f"{cfg.db_snapshot_max_age_days:.0f}d")
                out.append(c)
            out.sort(key=lambda c: c.mtime)   # oldest-first
        # Final cap across kinds so a single queue tick isn't unbounded.
        out = out[: max(0, cfg.max_per_kind)]
        # Cross-kind largest-first for emergency offload callers.
        return sorted(out, key=lambda c: c.size_bytes, reverse=True)

    def dry_run(self) -> Dict[str, List[Candidate]]:
        """Return ``{kind: [candidates]}`` for benchmark/echo without
        touching any DB or filesystem."""
        by_kind: Dict[str, List[Candidate]] = {k: [] for k in ALL_KINDS}
        for c in self.candidates():
            by_kind[c.kind].append(c)
        return by_kind

    # ----- introspection helpers -----
    def explain(self, path: str) -> str:
        """Tell a user why a file is or isn't eligible. Useful for CLI."""
        norm = os.path.normpath(path)
        exc = _is_excluded(norm)
        if exc:
            return f"excluded: {exc}"
        try:
            st = os.stat(norm)
        except OSError as exc:
            return f"stat failed: {exc}"
        info = [f"size={st.st_size}", f"mtime={st.st_mtime:.0f}"]
        kind = self._classify(norm)
        if kind is None:
            info.append("kind=unknown")
            return ", ".join(info)
        info.append(f"kind={kind}")
        if kind == KIND_RECORDING:
            age = (self._now_fn() - st.st_mtime) / 86400.0
            info.append(f"age={age:.1f}d, threshold="
                        f"{self.config.recording_max_age_days:.0f}d")
        elif kind == KIND_LOG:
            info.append(f"min_bytes={self.config.log_min_bytes}")
        elif kind == KIND_DB_SNAPSHOT:
            age = (self._now_fn() - st.st_mtime) / 86400.0
            info.append(f"age={age:.1f}d, threshold="
                        f"{self.config.db_snapshot_max_age_days:.0f}d")
        return ", ".join(info)

    def _classify(self, norm: str) -> Optional[str]:
        if glob.fnmatch.fnmatch(norm, self.config.recordings_glob):
            return KIND_RECORDING
        if glob.fnmatch.fnmatch(norm, self.config.logs_glob):
            return KIND_LOG
        if glob.fnmatch.fnmatch(norm, self.config.db_snapshot_glob):
            return KIND_DB_SNAPSHOT
        return None
