#!/usr/bin/env python3
"""The Tank Project — integration suite CLI.

Hosts 4 features (F146-F149):

* ``launch-check``       — assert that a launch file exists + arg count OK
* ``node-graph``         — emit a graphviz .dot for a launch file
* ``fault-inject``       — emit a fault-injection YAML
* ``snapshot-compare``   — diff two JSON snapshots (.topic_log-style)
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path



LOG_PREFIX = "[integration-suite]"


def _log(msg: str) -> None:
    print(f"{LOG_PREFIX} {msg}", flush=True)


def _ok(msg: str) -> None:
    print(f"{LOG_PREFIX} OK   {msg}", flush=True)


def _err(msg: str) -> None:
    print(f"{LOG_PREFIX} FAIL {msg}", file=sys.stderr, flush=True)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# F146 — launch-check
# ---------------------------------------------------------------------------
def cmd_launch_check(args: argparse.Namespace) -> int:
    """F146 — launch file check."""
    p = Path(args.path)
    if not p.exists():
        _err(f"missing: {p}")
        return 1
    text = p.read_text()
    nodes = text.count("Node(")
    actions = text.count("ExecuteProcess(") + text.count("action=LaunchAction")
    args_count = text.count("DeclareLaunchArgument")
    _ok(json.dumps({
        "path":  str(p),
        "lines": text.count("\n") + 1,
        "nodes": nodes,
        "actions": actions,
        "launch_args": args_count,
    }, indent=2))
    return 0


# ---------------------------------------------------------------------------
# F147 — node-graph
# ---------------------------------------------------------------------------
def cmd_node_graph(args: argparse.Namespace) -> int:
    """F147 — node graph .dot."""
    p = Path(args.path)
    if not p.exists():
        _err(f"missing: {p}")
        return 1
    text = p.read_text()
    nodes = []
    for ln in text.splitlines():
        if "Node(" in ln and "package=" in ln:
            nodes.append(ln.strip()[:120])
    out = Path(args.out or "tank_ws/data/node_graph.dot")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as fh:
        fh.write("digraph tank_nodes {\n  rankdir=LR;\n")
        for i, n in enumerate(nodes):
            fh.write(f'  "n{i}" [label="{n[:60]}"];\n')
        fh.write("}\n")
    _ok(f"wrote {out} ({len(nodes)} nodes)")
    return 0


# ---------------------------------------------------------------------------
# F148 — fault-inject
# ---------------------------------------------------------------------------
def cmd_fault_inject(args: argparse.Namespace) -> int:
    """F148 — fault injection spec."""
    spec = {
        "kind":    args.kind,
        "rate_pct": args.rate,
        "target":  args.target,
        "duration_s": args.duration,
        "ttl": args.ttl,
    }
    out = Path(args.out or "tank_ws/data/fault_inject.yaml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("# Generated by integration_suite.py fault-inject\n"
                   + json.dumps(spec, indent=2) + "\n")
    _ok(f"wrote {out}")
    return 0


# ---------------------------------------------------------------------------
# F149 — snapshot-compare
# ---------------------------------------------------------------------------
def cmd_snapshot_compare(args: argparse.Namespace) -> int:
    """F149 — JSON snapshot diff."""
    def load(path: Path) -> dict:
        try:
            return json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            _err(f"{path}: invalid JSON: {exc}")
            return {}
    a = load(Path(args.first))
    b = load(Path(args.second))
    if not a or not b:
        return 1
    keys = sorted(set(a) | set(b))
    diff = []
    for k in keys:
        av = a.get(k)
        bv = b.get(k)
        if av != bv:
            diff.append({"key": k, "first": av, "second": bv})
    _ok(json.dumps({"diff_count": len(diff), "diff": diff[:args.limit]},
                   indent=2, default=str))
    return 0 if not diff else 1


# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Integration suite (F146-F149).")
    sub = p.add_subparsers(dest="cmd", required=True)
    pl = sub.add_parser("launch-check", help="F146 — launch check")
    pl.add_argument("path")
    pn = sub.add_parser("node-graph", help="F147 — node graph")
    pn.add_argument("path")
    pn.add_argument("--out", default="")
    pf = sub.add_parser("fault-inject", help="F148 — fault inject spec")
    pf.add_argument("--kind", choices=("msg-loss", "latency", "kill-node", "estop"),
                    default="msg-loss")
    pf.add_argument("--rate", type=float, default=10.0)
    pf.add_argument("--target", default="/scan")
    pf.add_argument("--duration", type=int, default=30)
    pf.add_argument("--ttl", type=int, default=300)
    pf.add_argument("--out", default="")
    pc = sub.add_parser("snapshot-compare", help="F149 — snapshot diff")
    pc.add_argument("first")
    pc.add_argument("second")
    pc.add_argument("--limit", type=int, default=50)
    return p


HANDLERS = {
    "launch-check":    cmd_launch_check,
    "node-graph":      cmd_node_graph,
    "fault-inject":    cmd_fault_inject,
    "snapshot-compare":cmd_snapshot_compare,
}


def main(argv: Optional[list] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return HANDLERS[args.cmd](args)
    except KeyboardInterrupt:
        _err("interrupted")
        return 130


if __name__ == "__main__":
    sys.exit(main())
