#!/usr/bin/env python3
"""🔍 Model Auto-Finder — query every provider's API and discover available models.

Usage
-----
    python3 scripts/model_auto_finder.py
    python3 scripts/model_auto_finder.py --providers groq,mistral,cerebras
    python3 scripts/model_auto_finder.py --output-file /tmp/models.json
    python3 scripts/model_auto_finder.py --save-config   # updates concrete.py ENV defaults

The script loads all API keys from the environment (KeyRegistry chain),
queries each provider's models endpoint, and prints a colour-coded table
of what's available plus a rotation-ready JSON catalog.
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# Ensure the evolution module is importable
PROJECT_ROOT = Path(os.environ.get(
    "TANK_PROJECT_ROOT",
    "/root/the tank project",
))
TANK_WS_SRC = PROJECT_ROOT / "tank_ws" / "src"
if str(TANK_WS_SRC) not in sys.path:
    sys.path.insert(0, str(TANK_WS_SRC))

# ── Import the evolution model discovery module ──────────────────────────────
try:
    from tank_assistant.evolution.model_discovery import (
        ModelDiscoverer,
        DiscoveryResult,
    )
    from tank_assistant.evolution.key_registry import key_registry
    HAS_DISCOVERY = True
except ImportError as e:
    # Fallback: in-line minimal discovery for standalone use
    HAS_DISCOVERY = False
    import httpx  # type: ignore

    from dataclasses import dataclass, field
    from typing import List as _List, Optional as _Optional

    @dataclass
    class _FallbackResult:
        provider: str
        models: _List[str] = field(default_factory=list)
        error: _Optional[str] = None
        duration_s: float = 0.0
        stale: bool = False
    DiscoveryResult = _FallbackResult

    # Minimal fallback key loader from worker.env
    def _load_keys():
        env_file = Path("/etc/edulabs-thesis-worker/worker.env")
        if not env_file.exists():
            return
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                os.environ[k.strip()] = v.strip().strip("'\"")

    _load_keys()


# ── ANSI colours ─────────────────────────────────────────────────────────────

class Colours:
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    CYAN = "\033[96m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RESET = "\033[0m"


# ── Catalog output ───────────────────────────────────────────────────────────

def build_rotation_catalog(
    results: Dict[str, DiscoveryResult],
) -> Dict[str, Dict[str, Any]]:
    """Build a rotation-ready catalog from discovery results.

    Output format::

        {
          "groq": {
            "models": ["llama-3.3-70b-versatile", ...],
            "healthy": true,
            "default_model": "llama-3.3-70b-versatile",
            "updated_at": "2025-07-26T12:00:00"
          },
          ...
        }
    """
    now = time.strftime("%Y-%m-%dT%H:%M:%S")
    catalog: Dict[str, Dict[str, Any]] = {}
    for name, result in sorted(results.items()):
        models = result.models or []
        default = models[0] if models else None
        catalog[name] = {
            "models": models,
            "healthy": result.error is None and len(models) > 0,
            "default_model": default,
            "error": result.error,
            "duration_s": round(result.duration_s, 2),
            "updated_at": now,
        }
    return catalog


def format_rotation_config(catalog: Dict[str, Dict[str, Any]]) -> str:
    """Generate a formatted rotation config snippet for concrete.py."""
    lines = ["# Auto-generated by model_auto_finder.py",
             f"# Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}",
             ""]
    for name, info in sorted(catalog.items()):
        if not info["healthy"]:
            lines.append(f"# {name}: ❌ {info.get('error', 'no models')}")
            continue
        models = info["models"]
        default = info["default_model"]
        lines.append(f"# {name}: ✅ {len(models)} models")
        lines.append(f"#   DEFAULT_MODEL = {default}")
        lines.append(f"#   Available: {', '.join(models[:5])}{'...' if len(models) > 5 else ''}")
        lines.append(f"#   Export: export {name.upper()}_MODEL={default}")
        lines.append("")
    return "\n".join(lines)


def format_worker_js_fallback(catalog: Dict[str, Dict[str, Any]]) -> str:
    """Generate a JavaScript snippet for the worker.js fallbackCatalog."""
    lines = ["// Auto-generated fallback catalog snippet — paste into worker.js",
             f"// Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}",
             "const fallbackCatalog = {"]
    for name, info in sorted(catalog.items()):
        if not info["healthy"]:
            continue
        models = info["models"][:6]
        models_str = ", ".join(f'"{m}"' for m in models)
        lines.append(f"  {name}: [{models_str}],")
    lines.append("};")
    return "\n".join(lines)


# ── CLI ──────────────────────────────────────────────────────────────────────

def parse_args(argv: List[str]) -> dict:
    """Simple arg parser (no dependency on argparse for portability)."""
    args: Dict[str, Any] = {
        "providers": None,
        "output_file": None,
        "save_config": False,
        "timeout": 15.0,
        "format": "table",
    }
    i = 0
    while i < len(argv):
        if argv[i] == "--providers" and i + 1 < len(argv):
            args["providers"] = [p.strip() for p in argv[i + 1].split(",")]
            i += 1
        elif argv[i] == "--output-file" and i + 1 < len(argv):
            args["output_file"] = argv[i + 1]
            i += 1
        elif argv[i] == "--save-config":
            args["save_config"] = True
        elif argv[i] == "--timeout" and i + 1 < len(argv):
            args["timeout"] = float(argv[i + 1])
            i += 1
        elif argv[i] == "--format" and i + 1 < len(argv):
            args["format"] = argv[i + 1]
            i += 1
        elif argv[i] in ("-h", "--help"):
            print(__doc__)
            sys.exit(0)
        i += 1
    return args


def main(argv: List[str]) -> int:
    args = parse_args(argv[1:] if argv else [])
    timeout = args["timeout"]
    provider_filter = args["providers"]

    print()
    print(f"{Colours.BOLD}{'=' * 72}{Colours.RESET}")
    print(f"{Colours.CYAN}{Colours.BOLD}  🔍 Model Auto-Finder{Colours.RESET}")
    print(f"{Colours.BOLD}{'=' * 72}{Colours.RESET}")
    print()

    # ── Discover models ────────────────────────────────────────────────
    print(f"  {Colours.DIM}Discovering models from provider APIs...{Colours.RESET}")
    print()

    if HAS_DISCOVERY:
        discoverer = ModelDiscoverer(timeout_s=timeout)
        results = discoverer.discover_all(force=True, providers=provider_filter)
    else:
        print(f"  {Colours.YELLOW}⚠  Evolution module not found; using fallback in-line discoverer{Colours.RESET}")
        print()
        results = _fallback_discover(provider_filter, timeout)

    if not results:
        print(f"  {Colours.RED}✘{Colours.RESET} No results returned (no configured providers?)")
        return 1

    # ── Build catalog ───────────────────────────────────────────────────
    catalog = build_rotation_catalog(results)

    # ── Print table ─────────────────────────────────────────────────────
    healthy_count = sum(1 for r in catalog.values() if r["healthy"])
    total_count = len(catalog)

    print(f"  {Colours.BOLD}Provider{Colours.RESET}            Models  Status")
    print(f"  {'-' * 54}")

    for name, info in sorted(catalog.items()):
        models = info["models"]
        count = len(models)
        if info["healthy"]:
            icon = f"{Colours.GREEN}✅{Colours.RESET}"
            preview = models[0] if models else ""
        else:
            icon = f"{Colours.RED}❌{Colours.RESET}"
            preview = info.get("error", "unknown")[:40]

        print(f"  {icon} {name:18s} {count:3d}   {Colours.DIM}{preview}{Colours.RESET}")

    print(f"  {'-' * 54}")
    print(f"  {Colours.BOLD}Healthy:{Colours.RESET} {healthy_count}/{total_count}")
    print()

    # ── Save catalog ────────────────────────────────────────────────────
    if args["output_file"]:
        out_path = Path(args["output_file"])
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(catalog, indent=2), encoding="utf-8")
        print(f"  {Colours.GREEN}✔{Colours.RESET} Catalog saved to {out_path}")

    # ── Print rotation config snippets ─────────────────────────────────
    if args["format"] in ("all", "config"):
        print()
        print(f"{Colours.BOLD}  📋 Rotation Config (concrete.py){Colours.RESET}")
        print(f"  {Colours.DIM}{'─' * 60}{Colours.RESET}")
        print(f"  {format_rotation_config(catalog).replace(chr(10), chr(10) + '  ')}")

        print()
        print(f"{Colours.BOLD}  📋 Worker.js Fallback Catalog{Colours.RESET}")
        print(f"  {Colours.DIM}{'─' * 60}{Colours.RESET}")
        for line in format_worker_js_fallback(catalog).splitlines():
            print(f"  {line}")

        print()

    # ── Save config if requested ───────────────────────────────────────
    if args["save_config"]:
        _save_as_env_defaults(catalog)

    # ── Print JSON catalog ──────────────────────────────────────────────
    if args["format"] == "json":
        print(json.dumps(catalog, indent=2))

    return 0


# ── Fallback (when evolution module not available) ───────────────────────────

def _fallback_discover(provider_filter: Optional[List[str]],
                       timeout: float) -> Dict[str, DiscoveryResult]:
    """Minimal inline discoverer — mirrors the evolution module's logic."""
    import httpx

    FALLBACK_ENDPOINTS = {
        "groq": ("https://api.groq.com/openai/v1/models", "GROQ_API_KEY", ["data"]),
        "openrouter": ("https://openrouter.ai/api/v1/models", "OPENROUTER_API_KEY", ["data"]),
        "deepseek": ("https://api.deepseek.com/models", "DEEPSEEK_API_KEY", ["data"]),
        "mistral": ("https://api.mistral.ai/v1/models", "MISTRAL_API_KEY", ["data"]),
        "cohere": ("https://api.cohere.ai/v1/models", "COHERE_API_KEY", ["models"]),
        "cerebras": ("https://api.cerebras.ai/v1/models", "CEREBRAS_API_KEY", ["data"]),
    }

    results: Dict[str, DiscoveryResult] = {}
    client = httpx.Client(timeout=timeout)

    for name, (url, key_env, json_path) in FALLBACK_ENDPOINTS.items():
        if provider_filter and name not in provider_filter:
            continue
        key = os.environ.get(key_env, "")
        if not key:
            continue

        result = DiscoveryResult(provider=name)
        start = time.monotonic()
        try:
            headers = {"Authorization": f"Bearer {key}"}
            r = client.get(url, headers=headers)
            r.raise_for_status()
            data = r.json()
            # Navigate json_path
            current = data
            for k in json_path:
                current = current.get(k, [])
            model_ids = sorted(set(
                m.get("id", "") for m in (current or [])
                if isinstance(m, dict) and m.get("id")
            ))
            result.models = model_ids
        except Exception as exc:
            result.error = str(exc)[:200]
        result.duration_s = time.monotonic() - start
        results[name] = result

    client.close()
    return results


def _save_as_env_defaults(catalog: Dict[str, Dict[str, Any]]) -> None:
    """Save the discovered models as export statements for .env."""
    env_path = PROJECT_ROOT / ".env"
    existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    lines = existing.splitlines() if existing else []

    # Remove old auto-generated entries
    lines = [l for l in lines if not l.startswith("# auto-generated by model_auto_finder")]
    # Re-add entries for each healthy provider
    new_lines = [f"# auto-generated by model_auto_finder — {time.strftime('%Y-%m-%d %H:%M:%S')}"]
    for name, info in sorted(catalog.items()):
        if info["healthy"] and info["default_model"]:
            key = f"{name.upper()}_MODEL"
            val = info["default_model"]
            new_lines.append(f"export {key}={val}")
    lines = new_lines + ["", ""] + lines

    env_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  {Colours.GREEN}✔{Colours.RESET} Env defaults saved to {env_path}")


if __name__ == "__main__":
    sys.exit(main(sys.argv))
