#!/usr/bin/env python3
"""The Tank Project — network QoS CLI.

Hosts 3 features (F122-F124):

* ``shape-traffic``   — emit a tc qdisc script fragment
* ``dds-bandwidth``    — sample /proc/net/dev for DDS interface deltas
* ``latency-probe``    — periodic ping round-trip scatter
"""
from __future__ import annotations

import argparse
import json
import shutil
import statistics
import subprocess
import sys
import time
from pathlib import Path



LOG_PREFIX = "[net-qos]"


def _log(msg: str) -> None:
    print(f"{LOG_PREFIX} {msg}", flush=True)


def _ok(msg: str) -> None:
    print(f"{LOG_PREFIX} OK   {msg}", flush=True)


def _err(msg: str) -> None:
    print(f"{LOG_PREFIX} FAIL {msg}", file=sys.stderr, flush=True)


# ---------------------------------------------------------------------------
# F122 — shape-traffic
# ---------------------------------------------------------------------------
def cmd_shape_traffic(args: argparse.Namespace) -> int:
    """F122 — emit tc qdisc fragment."""
    rate = f"{int(args.mbps)}mbit"
    burst = max(args.burst_kb, 32)
    script = (
        f"#!/usr/bin/env bash\n"
        f"# Generated by scripts/net_qos.py shape-traffic\n"
        f"set -euo pipefail\n"
        f"IF={args.interface}\n"
        f"RATE={rate}\n"
        f"BURST={burst}\n"
        f"tc qdisc del dev $IF root 2>/dev/null || true\n"
        f"tc qdisc add dev $IF root tbf rate=$RATE burst=$BURST latency 50ms\n"
    )
    out = Path(args.out or f"/tmp/tc_{args.interface}.sh")
    out.write_text(script)
    out.chmod(0o755)
    _ok(f"wrote {out} ({rate} burst {burst} KB on {args.interface})")
    return 0


# ---------------------------------------------------------------------------
# F123 — dds-bandwidth
# ---------------------------------------------------------------------------
def cmd_dds_bandwidth(_: argparse.Namespace) -> int:
    """F123 — DDS interface bandwidth sample."""
    if shutil.which("ros2"):
        subprocess.call(["ros2", "topic", "bw", "/scan"])
        return 0
    try:
        with open("/proc/net/dev") as fh:
            before = {ln.split(":")[0].strip():
                      int(ln.split()[1])
                      for ln in fh if ":" in ln}
    except OSError as exc:
        _err(f"/proc/net/dev read failed: {exc}")
        return 1
    time.sleep(1.0)
    try:
        with open("/proc/net/dev") as fh:
            after = {ln.split(":")[0].strip():
                     int(ln.split()[1])
                     for ln in fh if ":" in ln}
    except OSError as exc:
        _err(f"/proc/net/dev re-read: {exc}")
        return 1
    diff = {iface: after.get(iface, 0) - before.get(iface, 0)
            for iface in after if iface in before}
    _ok(json.dumps({"rx_B_per_s": {k: v for k, v in diff.items()
                                  if k in ("lo", "wlan0", "eth0")}}, indent=2))
    return 0


# ---------------------------------------------------------------------------
# F124 — latency-probe
# ---------------------------------------------------------------------------
def cmd_latency_probe(args: argparse.Namespace) -> int:
    """F124 — latency probe."""
    if not shutil.which("ping"):
        _err("ping missing")
        return 1
    out = subprocess.run(["ping", "-c", str(args.count), "-W", "2",
                          args.peer],
                         capture_output=True, text=True, check=False)
    samples = []
    for line in out.stdout.splitlines():
        if "time=" in line:
            try:
                samples.append(float(line.split("time=")[1].split()[0]))
            except (ValueError, IndexError):
                pass
    if not samples:
        _err(f"no samples from {args.peer}")
        return 1
    _ok(json.dumps({
        "peer": args.peer,
        "count": len(samples),
        "min_ms": round(min(samples), 2),
        "avg_ms": round(statistics.mean(samples), 2),
        "max_ms": round(max(samples), 2),
        "p95_ms": round(statistics.quantiles(samples, n=20)[-1]
                       if len(samples) > 1 else max(samples), 2),
    }, indent=2))
    return 0


# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Net QoS CLI (F122-F124).")
    sub = p.add_subparsers(dest="cmd", required=True)
    ps = sub.add_parser("shape-traffic", help="F122 — tc qdisc")
    ps.add_argument("--interface", default="wlan0")
    ps.add_argument("--mbps", type=float, default=5.0)
    ps.add_argument("--burst-kb", type=int, default=32)
    ps.add_argument("--out", default="")
    sub.add_parser("dds-bandwidth", help="F123 — DDS bandwidth sample")
    pl = sub.add_parser("latency-probe", help="F124 — latency probe")
    pl.add_argument("--peer", required=True)
    pl.add_argument("--count", type=int, default=10)
    return p


HANDLERS = {
    "shape-traffic":  cmd_shape_traffic,
    "dds-bandwidth":  cmd_dds_bandwidth,
    "latency-probe":  cmd_latency_probe,
}


def main(argv: Optional[list] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return HANDLERS[args.cmd](args)
    except KeyboardInterrupt:
        _err("interrupted")
        return 130


if __name__ == "__main__":
    sys.exit(main())
