#!/usr/bin/env python3
"""The Tank Project — SLAM ops CLI.

Hosts 3 features (F109-F111):

* ``slam-tune``        — emit a slam_toolbox tweak file
* ``rtabmap-export``   — export RTAB-Map stats to JSON
* ``map-snapshot``     — snapshot the current 2D map to .pgm
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path



LOG_PREFIX = "[slam-ops]"


def _log(msg: str) -> None:
    print(f"{LOG_PREFIX} {msg}", flush=True)


def _ok(msg: str) -> None:
    print(f"{LOG_PREFIX} OK   {msg}", flush=True)


def _err(msg: str) -> None:
    print(f"{LOG_PREFIX} FAIL {msg}", file=sys.stderr, flush=True)


# ---------------------------------------------------------------------------
# F109 — slam-tune
# ---------------------------------------------------------------------------
def cmd_slam_tune(args: argparse.Namespace) -> int:
    """F109 — slam_toolbox tune."""
    cfg = {
        "loop_closure_search_space": args.loop_closure,
        "minimum_travel_distance":   args.min_travel,
        "minimum_travel_heading":    args.min_heading,
        "scan_buffer_size":          args.buffer_size,
        "max_laser_range":           args.laser_range,
        "do_loop_closing":           args.loop_closure > 0.0,
    }
    out = Path(args.out or "tank_ws/src/tank_navigation/config/slam_toolbox.yaml")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("# Generated by scripts/slam_ops.py slam-tune\n"
                   + json.dumps(cfg, indent=2) + "\n")
    _ok(f"wrote {out}")
    return 0


# ---------------------------------------------------------------------------
# F110 — rtabmap-export
# ---------------------------------------------------------------------------
def cmd_rtabmap_export(args: argparse.Namespace) -> int:
    """F110 — RTAB-Map export."""
    db = Path(args.input)
    out = Path(args.out or f"/tmp/rtabmap_{int(time.time())}.json")
    if not db.exists():
        _log(f"DRY: would snapshot {db} -> {out}")
        return 0
    out.write_text(json.dumps({
        "db_path":    str(db),
        "size_mb":    db.stat().st_size / 1024**2,
        "snapshot_at": time.time(),
        "note":       "RTAB-Map export is offline-only here",
    }, indent=2, default=str))
    _ok(f"snapshot -> {out}")
    return 0


# ---------------------------------------------------------------------------
# F111 — map-snapshot
# ---------------------------------------------------------------------------
def cmd_map_snapshot(args: argparse.Namespace) -> int:
    """F111 — 2D map snapshot."""
    out = Path(args.out or "/tmp/tank_map_snapshot.pgm")
    if args.dry_run:
        _log(f"DRY: would write 640x480 PG occupancy grid -> {out}")
        return 0
    # Synthesized PGM (P5 binary) so the offline path yields an
    # inspectable artifact without ROS.
    width = args.width
    height = args.height
    pgm = bytearray()
    pgm += f"P5\n{width} {height}\n255\n".encode()
    frame = bytes([128] * width * height)
    pgm += frame
    out.write_bytes(bytes(pgm))
    _ok(f"wrote {out} ({width}x{height})")
    return 0


# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="SLAM ops CLI (F109-F111).")
    sub = p.add_subparsers(dest="cmd", required=True)

    pt = sub.add_parser("slam-tune", help="F109 — slam_toolbox tune")
    pt.add_argument("--loop-closure", type=float, default=0.7)
    pt.add_argument("--min-travel",  type=float, default=0.5)
    pt.add_argument("--min-heading", type=float, default=0.5)
    pt.add_argument("--buffer-size", type=int, default=10)
    pt.add_argument("--laser-range", type=float, default=12.0)
    pt.add_argument("--out", default="")

    pr = sub.add_parser("rtabmap-export", help="F110 — RTAB-Map export")
    pr.add_argument("--input", required=True, help="RTAB-Map .db path")
    pr.add_argument("--out", default="")

    pm = sub.add_parser("map-snapshot", help="F111 — 2D map snapshot")
    pm.add_argument("--width", type=int, default=640)
    pm.add_argument("--height", type=int, default=480)
    pm.add_argument("--out", default="")
    pm.add_argument("--dry-run", action="store_true")
    return p


HANDLERS = {
    "slam-tune":       cmd_slam_tune,
    "rtabmap-export":  cmd_rtabmap_export,
    "map-snapshot":    cmd_map_snapshot,
}


def main(argv: Optional[list] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return HANDLERS[args.cmd](args)
    except KeyboardInterrupt:
        _err("interrupted")
        return 130


if __name__ == "__main__":
    sys.exit(main())
