#!/usr/bin/env python3
"""The Tank Project — vision ops CLI.

Hosts 4 features (F112-F115):

* ``yolo-tune``        — write YOLO config (conf, iou)
* ``tracker-state``    — dump YOLO tracker state
* ``depth-estimate``   — monocular MiDaS-style depth probe (offline
                         placeholder returning a uniform field)
* ``color-space``      — analyze a frame's hue / saturation histograms
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path



LOG_PREFIX = "[vision-ops]"


def _log(msg: str) -> None:
    print(f"{LOG_PREFIX} {msg}", flush=True)


def _ok(msg: str) -> None:
    print(f"{LOG_PREFIX} OK   {msg}", flush=True)


def _err(msg: str) -> None:
    print(f"{LOG_PREFIX} FAIL {msg}", file=sys.stderr, flush=True)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# F112 — yolo-tune
# ---------------------------------------------------------------------------
def cmd_yolo_tune(args: argparse.Namespace) -> int:
    """F112 — YOLO threshold tune."""
    cfg = {
        "model":      args.model,
        "confidence": args.conf,
        "iou":        args.iou,
        "classes":    [c.strip() for c in args.classes.split(",")] if args.classes else None,
        "device":     args.device,
    }
    out = _repo_root() / "tank_ws" / "src" / "tank_vision" / "config" / "yolo.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("# Generated by scripts/vision_ops.py yolo-tune\n"
                   + json.dumps(cfg, indent=2) + "\n")
    _ok(f"wrote {out}")
    return 0


# ---------------------------------------------------------------------------
# F113 — tracker-state
# ---------------------------------------------------------------------------
def cmd_tracker_state(_: argparse.Namespace) -> int:
    """F113 — tracker state dump."""
    _ok(json.dumps({
        "n_active_tracks": 0,
        "last_seen_age_s": None,
        "note":             "tracker_state is offline placeholder; ROS topic "
                            "/tracked_target is the authority on the Pi",
    }, indent=2))
    return 0


# ---------------------------------------------------------------------------
# F114 — depth-estimate
# ---------------------------------------------------------------------------
def cmd_depth_estimate(args: argparse.Namespace) -> int:
    """F114 — depth estimate (offline placeholder)."""
    frame = Path(args.frame)
    if not frame.exists():
        _err(f"frame missing: {frame}")
        return 1
    try:
        import cv2  # type: ignore
        import numpy as np  # type: ignore
        img = cv2.imread(str(frame))
        if img is None:
            _err(f"cv2 cannot read {frame}")
            return 1
        h, w = img.shape[:2]
        depth = np.full((h, w), 0.5, dtype=np.float32)
    except ImportError:
        depth = None
        _log("open-cv missing — would render uniform depth field 0.5 m")
    _ok(json.dumps({
        "frame": str(frame),
        "shape": list(depth.shape) if depth is not None else None,
        "depth_mean_m": 0.5,
        "note": "replace with MiDaS-small or depth-anything at deploy",
    }, indent=2))
    return 0


# ---------------------------------------------------------------------------
# F115 — color-space
# ---------------------------------------------------------------------------
def cmd_color_space(args: argparse.Namespace) -> int:
    """F115 — color-space probe (HSV histograms)."""
    frame = Path(args.frame)
    if not frame.exists():
        _err(f"frame missing: {frame}")
        return 1
    try:
        import cv2  # type: ignore
        import numpy as np  # type: ignore
        bgr = cv2.imread(str(frame))
        hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
        h_mean = float(hsv[..., 0].mean())
        s_mean = float(hsv[..., 1].mean())
        v_mean = float(hsv[..., 2].mean())
    except ImportError:
        h_mean = s_mean = v_mean = 0.0
        _log("opencv-python-headless missing — placeholder")
    _ok(json.dumps({
        "h_mean": round(h_mean, 2),
        "s_mean": round(s_mean, 2),
        "v_mean": round(v_mean, 2),
    }, indent=2))
    return 0


# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Vision ops CLI (F112-F115).")
    sub = p.add_subparsers(dest="cmd", required=True)

    py = sub.add_parser("yolo-tune", help="F112 — YOLO tune")
    py.add_argument("--conf", type=float, default=0.30)
    py.add_argument("--iou", type=float, default=0.50)
    py.add_argument("--classes", default="")
    py.add_argument("--model", default="yolov8n.pt")
    py.add_argument("--device", default="cpu")

    sub.add_parser("tracker-state", help="F113 — tracker state dump")

    pd = sub.add_parser("depth-estimate", help="F114 — depth estimate")
    pd.add_argument("--frame", required=True)

    pc = sub.add_parser("color-space", help="F115 — color-space probe")
    pc.add_argument("--frame", required=True)
    return p


HANDLERS = {
    "yolo-tune":      cmd_yolo_tune,
    "tracker-state":  cmd_tracker_state,
    "depth-estimate": cmd_depth_estimate,
    "color-space":    cmd_color_space,
}


def main(argv: Optional[list] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return HANDLERS[args.cmd](args)
    except KeyboardInterrupt:
        _err("interrupted")
        return 130


if __name__ == "__main__":
    sys.exit(main())
