"""TankOS Self-Coding AI System — autonomous code maintenance and improvement.

Daily cycle:
1. System health scan → 2. Log analysis → 3. Code knowledge refresh
4. Improvement planning → 5. Code generation → 6. Testing
7. Git backup + deploy → 8. Learning memory update

All changes go through: review → test → approve → deploy → verify.
Rollback is automatic on failure.
"""

from __future__ import annotations

import difflib
import json
import logging
import os
import re
import shutil
import subprocess
import sys
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from tank_os.core.event_bus import Event, EventBus

logger = logging.getLogger("tank_os.ai.self_coding")

REPO_ROOT = Path(os.environ.get("TANKOS_ROOT", "/root/the tank project"))
CODER_DIR = REPO_ROOT / "tank_os" / ".self_coding"


# ═══════════════════════════════════════════════════════════════════════════
# Data Models
# ═══════════════════════════════════════════════════════════════════════════

class ChangeStatus(Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEPLOYED = "deployed"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


@dataclass
class ChangeSet:
    """A proposed code change from the AI improvement system."""
    id: str
    description: str
    files: List[Dict[str, str]]  # [{"path": "...", "old": "...", "new": "..."}]
    reason: str
    category: str                # "bugfix", "optimization", "feature", "refactor"
    risk_level: str              # "low", "medium", "high", "critical"
    status: ChangeStatus = ChangeStatus.PENDING
    test_results: Dict[str, Any] = field(default_factory=dict)
    created: float = field(default_factory=time.time)
    deployed: Optional[float] = None
    author: str = "ai"           # "ai" or "user" or "agent"


@dataclass
class ImprovementTask:
    """A task generated by the improvement planner."""
    id: str
    description: str
    priority: int                # 1=high, 5=low
    source: str                  # "reflection", "health_check", "log_analysis", "user"
    related_files: List[str] = field(default_factory=list)
    suggested_fix: str = ""
    status: str = "pending"      # "pending", "in_progress", "completed", "skipped"


@dataclass
class HealthReport:
    """System health snapshot for the daily cycle."""
    timestamp: float
    cpu_percent: float
    memory_percent: float
    disk_percent: float
    temperature: float
    errors_found: int
    service_failures: List[str]
    ros_nodes: int
    uptime_hours: float
    score: float  # 0-100


# ═══════════════════════════════════════════════════════════════════════════
# Self-Coding System
# ═══════════════════════════════════════════════════════════════════════════

class SelfCodingSystem:
    """Autonomous self-coding system that improves TankOS daily.

    Integrates: DiagnosticsManager, ReflectionEngine, MemoryManager,
    CodingAgent, Git, and external coding agents.

    Usage:
        system = SelfCodingSystem()
        system.initialize()
        system.run_daily_cycle()  # Run the full daily cycle
    """

    _instance: Optional["SelfCodingSystem"] = None
    _lock = threading.Lock()

    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._bus = EventBus()
                cls._instance._change_sets: List[ChangeSet] = []
                cls._instance._tasks: List[ImprovementTask] = []
                cls._instance._health_history: List[HealthReport] = []
                cls._instance._cycle_running = False
                cls._instance._auto_mode = False
                cls._instance._cycle_count = 0
                cls._instance._store_path = CODER_DIR / "self_coding.json"
                cls._instance._sandbox_dir = CODER_DIR / "sandbox"
                cls._instance._code_index = {}
                cls._instance._last_code_scan = 0.0
                cls._instance._models_available = []
                cls._instance._db_path = REPO_ROOT / "tank_os" / ".self_coding" / "learned_fixes.json"
            return cls._instance

    # ── Initialization ───────────────────────────────────────────────

    def initialize(self) -> None:
        """Initialize the self-coding system."""
        self._ensure_dirs()
        self._load()
        self._detect_coding_models()
        self._bus.on("daily_tick", self._on_daily_tick)
        self._bus.on("self_coding_request", self._on_request)
        logger.info("SelfCodingSystem initialized (%d changes, %d tasks, %d cycles)",
                     len(self._change_sets), len(self._tasks), self._cycle_count)

    def _ensure_dirs(self) -> None:
        CODER_DIR.mkdir(parents=True, exist_ok=True)
        self._sandbox_dir.mkdir(parents=True, exist_ok=True)

    def _load(self) -> None:
        if self._store_path.exists():
            try:
                data = json.loads(self._store_path.read_text())
                self._change_sets = [ChangeSet(**c) for c in data.get("changes", [])]
                self._tasks = [ImprovementTask(**t) for t in data.get("tasks", [])]
                self._cycle_count = data.get("cycle_count", 0)
            except Exception as e:
                logger.warning("Failed to load self-coding state: %s", e)

    def _save(self) -> None:
        self._store_path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "changes": [vars(c) for c in self._change_sets[-100:]],
            "tasks": [vars(t) for t in self._tasks[-200:]],
            "cycle_count": self._cycle_count,
            "last_update": time.time(),
        }
        self._store_path.write_text(json.dumps(data, indent=2, default=str))

    # ═══════════════════════════════════════════════════════════════════
    # 1. System Monitor — health scan
    # ═══════════════════════════════════════════════════════════════════

    def scan_health(self) -> HealthReport:
        """Collect comprehensive system health data."""
        try:
            from tank_os.core.diagnostics_manager import DiagnosticsManager
            dm = DiagnosticsManager()
            d = dm.collect()
        except Exception:
            d = {}

        cpu = d.get("cpu", {}).get("percent", 0.0) or 0.0
        mem = d.get("memory", {}).get("percent", 0.0) or 0.0
        disk = d.get("disk", {}).get("percent", 0.0) or 0.0
        temp = d.get("temperature", {}).get("cpu_c", 0.0) or 0.0
        uptime = d.get("uptime", 0.0) or 0.0
        ros_nodes = d.get("ros", {}).get("node_count", 0) or 0
        services = self._check_services()
        errors = self._count_recent_errors()

        # Calculate health score (0-100)
        score = 100.0
        if cpu > 80: score -= 15
        if mem > 85: score -= 15
        if disk > 90: score -= 20
        if temp > 75: score -= 15
        if errors > 0: score -= min(20, errors * 5)
        if services: score -= min(15, len(services) * 5)
        score = max(0, score)

        report = HealthReport(
            timestamp=time.time(),
            cpu_percent=cpu,
            memory_percent=mem,
            disk_percent=disk,
            temperature=temp,
            errors_found=errors,
            service_failures=services,
            ros_nodes=ros_nodes,
            uptime_hours=uptime / 3600,
            score=score,
        )
        self._health_history.append(report)
        if len(self._health_history) > 90:
            self._health_history.pop(0)
        return report

    def _check_services(self) -> List[str]:
        """Check critical systemd services."""
        failed: List[str] = []
        for svc in ["tank-init", "mosquitto", "nginx", "docker"]:
            try:
                r = subprocess.run(
                    ["systemctl", "is-active", f"{svc}.service"],
                    capture_output=True, text=True, timeout=3,
                )
                if r.stdout.strip() != "active":
                    failed.append(svc)
            except Exception:
                continue
        return failed

    def _count_recent_errors(self) -> int:
        """Count errors in recent TankOS logs."""
        count = 0
        try:
            r = subprocess.run(
                ["journalctl", "-u", "tank-init.service", "--since", "24h",
                 "--priority", "err", "--no-pager"],
                capture_output=True, text=True, timeout=5,
            )
            count = len([l for l in r.stdout.splitlines() if l.strip()])
        except Exception:
            pass
        return count

    # ═══════════════════════════════════════════════════════════════════
    # 2. Code Knowledge Engine — index source code
    # ═══════════════════════════════════════════════════════════════════

    def scan_codebase(self) -> Dict[str, Any]:
        """Index the TankOS codebase for AI understanding."""
        now = time.time()
        if now - self._last_code_scan < 300:  # Cache for 5 min
            return self._code_index

        index: Dict[str, Any] = {
            "files": {}, "modules": [], "classes": [],
            "functions": [], "total_lines": 0, "errors": [],
        }

        for py_file in sorted(REPO_ROOT.rglob("**/*.py")):
            if any(p.startswith(".") for p in py_file.parts):
                continue
            if "__pycache__" in py_file.parts:
                continue
            rel = py_file.relative_to(REPO_ROOT)
            try:
                content = py_file.read_text(encoding="utf-8", errors="replace")
                lines = content.splitlines()
                index["total_lines"] += len(lines)
                index["files"][str(rel)] = {
                    "lines": len(lines),
                    "size": len(content),
                    "classes": self._extract_classes(content),
                    "functions": self._extract_functions(content),
                    "imports": self._extract_imports(content),
                    "docstring": self._extract_docstring(content),
                }
                index["classes"].extend(self._extract_classes(content))
                index["functions"].extend(self._extract_functions(content))
                if str(rel).startswith("tank_os/"):
                    index["modules"].append(str(rel))
            except Exception as e:
                index["errors"].append(f"{rel}: {e}")

        self._code_index = index
        self._last_code_scan = now
        return index

    def _extract_classes(self, content: str) -> List[Dict[str, Any]]:
        classes = []
        for m in re.finditer(r"^class (\w+)(?:\((\w+)\))?:", content, re.MULTILINE):
            class_name = m.group(1)
            parent = m.group(2) or ""
            # Get line number
            line_num = content[:m.start()].count("\n") + 1
            classes.append({"name": class_name, "parent": parent, "line": line_num})
        return classes

    def _extract_functions(self, content: str) -> List[Dict[str, Any]]:
        functions = []
        for m in re.finditer(r"^\s+def (\w+)\(([^)]*)\)\s*(?:->\s*(\w+))?:",
                             content, re.MULTILINE):
            func_name = m.group(1)
            params = m.group(2)
            return_type = m.group(3) or ""
            line_num = content[:m.start()].count("\n") + 1
            if not func_name.startswith("_"):
                functions.append({
                    "name": func_name, "params": params,
                    "return_type": return_type, "line": line_num,
                })
        return functions

    def _extract_imports(self, content: str) -> List[str]:
        imports = []
        for m in re.finditer(r"^(?:from\s+(\S+)\s+)?import\s+(.+)",
                             content, re.MULTILINE):
            module = m.group(1) or ""
            names = m.group(2)
            imports.append(f"{module}:{names}" if module else names)
        return imports[:20]

    def _extract_docstring(self, content: str) -> str:
        m = re.match(r'^"""(.+?)"""', content, re.DOTALL)
        return m.group(1).strip()[:200] if m else ""

    def search_code(self, query: str, limit: int = 10) -> List[Dict[str, Any]]:
        """Search codebase for relevant files."""
        results = []
        if not self._code_index:
            self.scan_codebase()
        q = query.lower()
        for path, info in self._code_index.get("files", {}).items():
            score = 0
            if q in path.lower(): score += 3
            for cls in info.get("classes", []):
                if q in cls["name"].lower(): score += 2
            for fn in info.get("functions", []):
                if q in fn["name"].lower(): score += 2
            if q in info.get("docstring", "").lower(): score += 1
            if score > 0:
                results.append({"path": path, "score": score, **info})
        results.sort(key=lambda x: -x["score"])
        return results[:limit]

    # ═══════════════════════════════════════════════════════════════════
    # 3. AI Improvement Planner — analyze and plan changes
    # ═══════════════════════════════════════════════════════════════════

    def plan_improvements(self, health: HealthReport) -> List[ImprovementTask]:
        """Analyze system health + logs + reflections and plan improvements."""
        tasks: List[ImprovementTask] = []

        # From health check
        if health.cpu_percent > 80:
            tasks.append(ImprovementTask(
                id=str(uuid.uuid4())[:8],
                description=f"High CPU usage ({health.cpu_percent}%) — investigate and optimize",
                priority=2, source="health_check",
                suggested_fix="Check for runaway processes, add throttling",
            ))
        if health.memory_percent > 85:
            tasks.append(ImprovementTask(
                id=str(uuid.uuid4())[:8],
                description=f"High memory usage ({health.memory_percent}%) — optimize memory",
                priority=3, source="health_check",
                suggested_fix="Review memory leaks, add cache limits",
            ))
        if health.disk_percent > 90:
            tasks.append(ImprovementTask(
                id=str(uuid.uuid4())[:8],
                description=f"Low disk space ({health.disk_percent}%) — clean up",
                priority=1, source="health_check",
                suggested_fix="Remove old logs, compress data files",
            ))
        if health.temperature > 75:
            tasks.append(ImprovementTask(
                id=str(uuid.uuid4())[:8],
                description=f"High temperature ({health.temperature}°C) — reduce load",
                priority=2, source="health_check",
            ))
        for svc in health.service_failures:
            tasks.append(ImprovementTask(
                id=str(uuid.uuid4())[:8],
                description=f"Service {svc} not running — investigate",
                priority=1, source="health_check", status="in_progress",
            ))

        # From reflection engine
        try:
            from tank_os.ai.reflection_engine import ReflectionEngine
            ref = ReflectionEngine()
            goals = ref.get_active_goals()
            for g in goals[:3]:
                tasks.append(ImprovementTask(
                    id=str(uuid.uuid4())[:8],
                    description=g.description,
                    priority=3, source="reflection",
                    suggested_fix=g.recommended_action,
                ))
        except Exception:
            pass

        # From log analysis
        log_issues = self._analyze_logs()
        for issue in log_issues[:3]:
            tasks.append(ImprovementTask(
                id=str(uuid.uuid4())[:8],
                description=issue,
                priority=3, source="log_analysis",
            ))

        self._tasks.extend(tasks)
        self._save()
        return tasks

    def _analyze_logs(self) -> List[str]:
        """Analyze recent logs for issues."""
        issues = []
        try:
            r = subprocess.run(
                ["journalctl", "-u", "tank-init.service", "--since", "24h",
                 "--priority", "warning", "--no-pager"],
                capture_output=True, text=True, timeout=5,
            )
            lines = [l for l in r.stdout.splitlines() if l.strip()]
            # Group by common patterns
            patterns = {
                "Failed to import": "Import errors in critical modules",
                "Timeout": "Service timeouts detected",
                "Connection refused": "Network connectivity issues",
                "Traceback": "Python exceptions in service logs",
                "OOM": "Out of memory events",
            }
            found = set()
            for line in lines:
                for key, desc in patterns.items():
                    if key in line and key not in found:
                        issues.append(desc)
                        found.add(key)
        except Exception:
            pass
        return issues

    # ═══════════════════════════════════════════════════════════════════
    # 4. Code Generation Engine — generate code changes
    # ═══════════════════════════════════════════════════════════════════

    def generate_fix(self, task: ImprovementTask) -> Optional[ChangeSet]:
        """Generate a code fix for an improvement task."""
        # Find relevant files
        code_results = self.search_code(task.description)

        if task.source == "health_check" and "service" in task.description.lower():
            return self._generate_service_fix(task)

        if task.source == "reflection":
            return self._generate_reflection_fix(task)

        return self._generate_generic_fix(task, code_results)

    def _generate_service_fix(self, task: ImprovementTask) -> Optional[ChangeSet]:
        """Generate a notification/recommendation for a failed service.

        Instead of overwriting service files, this creates a metadata-only
        ChangeSet that the deploy step logs as a manual-action recommendation.
        """
        for svc_name in task.description.split():
            svc_clean = svc_name.strip(",.!")
            svc_file = REPO_ROOT / "tank_os" / "startup" / f"{svc_clean}.service"
            exists = svc_file.exists()
            return ChangeSet(
                id=str(uuid.uuid4())[:8],
                description=f"Restart and verify {svc_clean} service",
                files=[{
                    "path": f"recommendation:{svc_clean}",
                    "old": "",  # No file modification — operational recommendation
                    "new": f"# Recommendation: restart {svc_clean} service\n# systemctl restart {svc_clean}\nsvc_exists={exists}",
                }],
                reason=task.description,
                category="bugfix",
                risk_level="low",
            )
        return None

    def _generate_reflection_fix(self, task: ImprovementTask) -> Optional[ChangeSet]:
        """Generate a fix based on reflection insights."""
        desc = task.description.lower()
        changes = []

        # Check for common patterns
        if "navigation" in desc:
            nav_file = REPO_ROOT / "tank_os" / "core" / "navigation_manager.py"
            if nav_file.exists():
                content = nav_file.read_text()
                changes.append({
                    "path": str(nav_file.relative_to(REPO_ROOT)),
                    "old": "except Exception:",
                    "new": "except Exception as e:\n            logger.warning(\"Navigation error: %s\", e)",
                })

        if changes:
            return ChangeSet(
                id=str(uuid.uuid4())[:8],
                description=task.description[:100],
                files=changes,
                reason=task.suggested_fix or task.description,
                category="bugfix",
                risk_level="medium" if "safety" in desc else "low",
            )
        return None

    def _generate_generic_fix(self, task: ImprovementTask,
                               code_results: List[Dict]) -> Optional[ChangeSet]:
        """Generate a generic fix suggestion."""
        if not code_results:
            return None
        best = code_results[0]
        path = best.get("path", "")
        return ChangeSet(
            id=str(uuid.uuid4())[:8],
            description=f"Review and improve: {task.description[:80]}",
            files=[{"path": path, "old": "", "new": "/* review needed */"}],
            reason=task.description,
            category="optimization" if "optimize" in task.description.lower() else "bugfix",
            risk_level="low",
            status=ChangeStatus.PENDING,
        )

    def _detect_coding_models(self) -> None:
        """Detect available coding models for code generation."""
        llm_dir = Path("/var/lib/tank_os/models/llm")
        if llm_dir.exists():
            models = list(llm_dir.glob("*coder*gguf")) + list(llm_dir.glob("*Coder*gguf"))
            self._models_available = [m.name for m in models]

    # ═══════════════════════════════════════════════════════════════════
    # 5. Testing Sandbox — test changes before deploy
    # ═══════════════════════════════════════════════════════════════════

    def test_change(self, change: ChangeSet) -> Dict[str, Any]:
        """Test a change set in the sandbox before deploying."""
        results = {"passed": True, "tests_run": 0, "failed": 0, "errors": []}

        for file_info in change.files:
            path = file_info.get("path", "")
            file_path = REPO_ROOT / path
            if not file_path.exists():
                continue

            # Syntax check
            if path.endswith(".py"):
                try:
                    compile(file_path.read_text(), str(file_path), "exec")
                    results["tests_run"] += 1
                except SyntaxError as e:
                    results["passed"] = False
                    results["failed"] += 1
                    results["errors"].append(f"Syntax error in {path}: {e}")

            # Import check — use isolated import to avoid polluting sys.modules
            if path.endswith(".py") and path.startswith("tank_os/"):
                mod_name = path.replace("/", ".").replace(".py", "")
                try:
                    import importlib.util
                    spec = importlib.util.spec_from_file_location(mod_name, file_path)
                    if spec and spec.loader:
                        mod = importlib.util.module_from_spec(spec)
                        spec.loader.exec_module(mod)
                        # Clean up from sys.modules to avoid side effects
                        if mod_name in sys.modules:
                            del sys.modules[mod_name]
                    results["tests_run"] += 1
                except Exception as e:
                    results["errors"].append(f"Import error in {path}: {e}")
                    results["failed"] += 1

        # Run existing pytest for affected module
        if change.files:
            test_dir = REPO_ROOT / "tank_os" / "tests"
            if test_dir.exists():
                try:
                    r = subprocess.run(
                        ["python3", "-m", "pytest", str(test_dir), "--tb=short",
                         "-q", "--timeout=30"],
                        capture_output=True, text=True, timeout=60,
                    )
                    results["pytest_output"] = r.stdout[-500:] if len(r.stdout) > 500 else r.stdout
                    if r.returncode != 0:
                        results["passed"] = False
                        results["failed"] += 1
                except Exception:
                    pass

        change.test_results = results
        return results

    # ═══════════════════════════════════════════════════════════════════
    # 6. Version Control Manager — Git backup/rollback
    # ═══════════════════════════════════════════════════════════════════

    def git_snapshot(self, message: str = "auto") -> bool:
        """Create a Git snapshot before changes."""
        try:
            branch = f"auto-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
            subprocess.run(["git", "checkout", "-b", branch],
                           cwd=REPO_ROOT, capture_output=True, timeout=10)
            subprocess.run(["git", "add", "-A"],
                           cwd=REPO_ROOT, capture_output=True, timeout=10)
            subprocess.run(
                ["git", "commit", "-m", f"[auto] {message} - {datetime.now().isoformat()}"],
                cwd=REPO_ROOT, capture_output=True, timeout=10,
            )
            subprocess.run(["git", "checkout", "-"],
                           cwd=REPO_ROOT, capture_output=True, timeout=10)
            logger.info("Git snapshot created: %s", branch)
            return True
        except Exception as e:
            logger.warning("Git snapshot failed: %s", e)
            return False

    def git_rollback(self, commit_hash: str = "HEAD~1") -> bool:
        """Rollback to a previous commit."""
        try:
            subprocess.run(["git", "checkout", commit_hash, "--", "."],
                           cwd=REPO_ROOT, capture_output=True, timeout=30)
            logger.info("Rollback to %s completed", commit_hash)
            return True
        except Exception as e:
            logger.warning("Rollback failed: %s", e)
            return False

    # ═══════════════════════════════════════════════════════════════════
    # 7. Auto Deployment Manager — apply + verify
    # ═══════════════════════════════════════════════════════════════════

    def deploy_change(self, change: ChangeSet) -> bool:
        """Apply a change, verify, and handle rollback if needed."""
        if change.status not in (ChangeStatus.PENDING, ChangeStatus.APPROVED):
            logger.warning("Change %s is not in deployable state", change.id)
            return False

        # Create backup
        backups = {}
        for file_info in change.files:
            path = file_info.get("path", "")
            # Skip recommendation-only entries (e.g. service restart suggestions)
            if path.startswith("recommendation:"):
                continue
            file_path = REPO_ROOT / path
            if file_path.exists():
                backups[path] = file_path.read_text()

        # Apply changes
        try:
            for file_info in change.files:
                path = file_info.get("path", "")
                if path.startswith("recommendation:"):
                    continue
                file_path = REPO_ROOT / path
                new_content = file_info.get("new", "")
                if new_content:
                    file_path.parent.mkdir(parents=True, exist_ok=True)
                    file_path.write_text(new_content)
            change.status = ChangeStatus.DEPLOYED
            change.deployed = time.time()
            self._bus.emit(Event("change_deployed", {
                "id": change.id, "description": change.description,
            }, source="self_coding"))
            self._save()
            return True
        except Exception as e:
            logger.error("Deploy failed for %s: %s", change.id, e)
            # Rollback
            for path, content in backups.items():
                try:
                    (REPO_ROOT / path).write_text(content)
                except Exception:
                    pass
            change.status = ChangeStatus.ROLLED_BACK
            self._save()
            return False

    def verify_deployment(self, change: ChangeSet) -> bool:
        """Verify a deployed change is working correctly."""
        try:
            # Re-import affected modules
            for file_info in change.files:
                path = file_info.get("path", "")
                if path.endswith(".py") and path.startswith("tank_os/"):
                    mod = path.replace("/", ".").replace(".py", "")
                    try:
                        __import__(mod, fromlist=["dummy"])
                    except Exception as e:
                        logger.error("Post-deploy import failed: %s", e)
                        return False

            # Re-run health check
            health = self.scan_health()
            if health.errors_found > 0:
                logger.warning("New errors detected after deploy")
                return False

            logger.info("Deployment verified for %s", change.id)
            return True
        except Exception as e:
            logger.error("Verification failed: %s", e)
            return False

    # ═══════════════════════════════════════════════════════════════════
    # 8. Learning Memory — store fixes for future reference
    # ═══════════════════════════════════════════════════════════════════

    def learn_from_change(self, change: ChangeSet) -> None:
        """Store the fix in learning memory for future reference."""
        if change.status != ChangeStatus.DEPLOYED:
            return

        entry = {
            "id": change.id,
            "description": change.description,
            "category": change.category,
            "files": [f["path"] for f in change.files],
            "reason": change.reason,
            "timestamp": time.time(),
            "success": True,
        }

        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        history = []
        if self._db_path.exists():
            try:
                history = json.loads(self._db_path.read_text())
            except Exception:
                pass
        history.append(entry)
        if len(history) > 200:
            history = history[-200:]
        self._db_path.write_text(json.dumps(history, indent=2, default=str))

    def get_learned_fixes(self, query: str = "", limit: int = 10) -> List[Dict[str, Any]]:
        """Retrieve past fixes similar to a query."""
        if not self._db_path.exists():
            return []
        try:
            history = json.loads(self._db_path.read_text())
            if query:
                q = query.lower()
                scored = []
                for h in history:
                    score = 0
                    if q in h.get("description", "").lower(): score += 3
                    if q in h.get("reason", "").lower(): score += 2
                    if q in " ".join(h.get("files", [])).lower(): score += 1
                    if score > 0:
                        scored.append((score, h))
                scored.sort(key=lambda x: -x[0])
                return [h for _, h in scored[:limit]]
            return history[-limit:]
        except Exception:
            return []

    # ═══════════════════════════════════════════════════════════════════
    # 9. Complete Daily Cycle
    # ═══════════════════════════════════════════════════════════════════

    def run_daily_cycle(self) -> Dict[str, Any]:
        """Run the complete daily self-improvement cycle."""
        if self._cycle_running:
            return {"status": "already_running"}
        self._cycle_running = True
        self._cycle_count += 1
        start = time.time()
        results: Dict[str, Any] = {"cycle": self._cycle_count, "timestamp": start}

        try:
            logger.info("=== Self-Coding Cycle #%d ===", self._cycle_count)

            # Step 1: Scan health
            health = self.scan_health()
            results["health"] = {"score": health.score, "errors": health.errors_found}
            logger.info("Health: %d/100, %d errors", health.score, health.errors_found)

            # Step 2: Update code knowledge
            code_index = self.scan_codebase()
            results["code_files"] = len(code_index.get("files", {}))
            logger.info("Code index: %d files", len(code_index.get("files", {})))

            # Step 3: Plan improvements
            tasks = self.plan_improvements(health)
            results["tasks_planned"] = len(tasks)
            logger.info("Tasks planned: %d", len(tasks))

            # Step 4: Generate fixes for high-priority tasks
            deployed = 0
            for task in sorted(tasks, key=lambda t: t.priority)[:3]:
                if task.status == "completed":
                    continue

                logger.info("Working on: %s", task.description[:60])
                change = self.generate_fix(task)
                if not change:
                    logger.info("  No fix generated")
                    continue

                # Step 5: Test
                test_results = self.test_change(change)
                if not test_results.get("passed", False):
                    logger.warning("  Tests failed: %s", test_results.get("errors"))
                    change.status = ChangeStatus.REJECTED
                    task.status = "skipped"
                    continue

                # Step 6: Approve if low risk
                if change.risk_level in ("low", "medium"):
                    change.status = ChangeStatus.APPROVED
                else:
                    change.status = ChangeStatus.PENDING  # Needs human review
                    logger.info("  High risk — requires approval")
                    continue

                # Step 7: Deploy
                if change.status == ChangeStatus.APPROVED:
                    if self.deploy_change(change):
                        # Step 8: Verify
                        if self.verify_deployment(change):
                            task.status = "completed"
                            deployed += 1
                            # Step 9: Learn
                            self.learn_from_change(change)
                            logger.info("  ✅ Deployed and verified")
                        else:
                            self.git_rollback()
                            change.status = ChangeStatus.ROLLED_BACK
                            logger.warning("  ❌ Verification failed — rolled back")
                    else:
                        logger.warning("  ❌ Deploy failed")

            results["deployed"] = deployed
            results["total_changes"] = len(self._change_sets)

            # Step 10: Git snapshot
            self.git_snapshot(f"daily-cycle-{self._cycle_count}")

            self._bus.emit(Event("self_coding_cycle_complete", {
                "cycle": self._cycle_count, "deployed": deployed,
                "health_score": health.score, "duration": time.time() - start,
            }, source="self_coding"))

        except Exception as e:
            logger.exception("Daily cycle failed: %s", e)
            results["error"] = str(e)
        finally:
            self._cycle_running = False

        results["duration_s"] = round(time.time() - start, 1)
        self._save()
        logger.info("Cycle #%d complete in %.1fs (%d deployed)",
                     self._cycle_count, results["duration_s"], results.get("deployed", 0))
        return results

    def _on_daily_tick(self, event: Event) -> None:
        """Run daily cycle on daily tick."""
        if self._auto_mode:
            self.run_daily_cycle()

    def _on_request(self, event: Event) -> None:
        """Handle manual request from EventBus."""
        action = event.data.get("action", "cycle")
        if action == "cycle":
            self.run_daily_cycle()
        elif action == "health":
            health = self.scan_health()
            self._bus.emit(Event("self_coding_health", {
                "score": health.score, "errors": health.errors_found,
            }, source="self_coding"))

    # ═══════════════════════════════════════════════════════════════════
    # Query API
    # ═══════════════════════════════════════════════════════════════════

    def get_status(self) -> Dict[str, Any]:
        """Get full system status."""
        return {
            "cycle_count": self._cycle_count,
            "total_changes": len(self._change_sets),
            "pending_changes": len([c for c in self._change_sets if c.status == ChangeStatus.PENDING]),
            "deployed_changes": len([c for c in self._change_sets if c.status == ChangeStatus.DEPLOYED]),
            "active_tasks": len([t for t in self._tasks if t.status == "pending"]),
            "health_history": len(self._health_history),
            "code_files": len(self._code_index.get("files", {})),
            "learned_fixes": self._db_path.exists(),
            "auto_mode": self._auto_mode,
            "cycle_running": self._cycle_running,
        }

    def get_pending_changes(self) -> List[ChangeSet]:
        """Get changes waiting for approval."""
        return [c for c in self._change_sets if c.status == ChangeStatus.PENDING]

    def approve_change(self, change_id: str) -> bool:
        """Approve a pending change for deployment."""
        for c in self._change_sets:
            if c.id == change_id and c.status == ChangeStatus.PENDING:
                c.status = ChangeStatus.APPROVED
                self._save()
                return True
        return False

    def reject_change(self, change_id: str) -> bool:
        """Reject a pending change."""
        for c in self._change_sets:
            if c.id == change_id:
                c.status = ChangeStatus.REJECTED
                self._save()
                return True
        return False

    def get_health_trend(self, days: int = 7) -> List[Dict[str, Any]]:
        """Get health score trend."""
        cutoff = time.time() - days * 86400
        return [
            {"timestamp": h.timestamp, "score": h.score, "errors": h.errors_found}
            for h in self._health_history if h.timestamp >= cutoff
        ]

    def get_summary(self) -> Dict[str, Any]:
        """Brief summary."""
        return self.get_status()
